### ISSUE TITLE
Misleading error message

### ISSUE THREAD

**Issue by yaelbh** [Qiskit-Extensions/qiskit-ibm-experiment#84]
I don't know if this is the correct repository for this issue.

We've had a case where apparently a user without access permission to the result database tried to save an experiment. The error message that the user received was misleading:
```
Unable to save the experiment data: Traceback (most recent call last):
  File "/home/labuser/.virtualenvs/controller/lib/python3.8/site-packages/qiskit_experiments/framework/experiment_data.py", line 1354, in _save_experiment_metadata
    self.service.create_or_update_experiment(
  File "/home/labuser/.virtualenvs/controller/lib/python3.8/site-packages/qiskit_ibm_experiment/service/ibm_experiment_service.py", line 402, in create_or_update_experiment
    return self.create_or_update(
  File "/home/labuser/.virtualenvs/controller/lib/python3.8/site-packages/qiskit_ibm_experiment/service/ibm_experiment_service.py", line 1573, in create_or_update
    result = create_func(**params)
  File "/home/labuser/.virtualenvs/controller/lib/python3.8/site-packages/qiskit_ibm_experiment/service/ibm_experiment_service.py", line 343, in create_experiment
    response_data = self._api_client.experiment_upload(
  File "/usr/lib64/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/labuser/.virtualenvs/controller/lib/python3.8/site-packages/qiskit_ibm_experiment/service/utils.py", line 45, in map_api_error
    raise IBMApiError(
qiskit_ibm_experiment.exceptions.IBMApiError: 'Failed to process the request: The server responded with \'400 Client Error: Bad Request for url: https://resultsdb.quantum-computing.ibm.com/experiments. {"errors":["Device test_sapporo either does not exist or is not available"]}\''
```

**Comment by gadial** [comment]
The client reports back the errors sent by the server, but in general does not parse them further, since they are not informative enough to fully understand the error (as in this case). I think this should be handled server-side, with an update to `qiskit-ibm-experiment` following.

**Comment by coruscating** [comment]
This has been fixed server-side and can be closed.
